name: smarttextile
description: Smart Textile Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #for different types of fonts
  google_fonts: ^1.1.0
  firebase_storage: ^3.1.6
  animate_do: ^1.7.2
  clip_shadow: ^0.2.1
  shimmer: ^1.1.1
  flare_flutter: ^2.0.5
  firebase_messaging: ^6.0.16
  carousel_slider: ^2.2.1
  image_picker: ^0.6.7+4
  badges: ^1.1.1
  provider: ^4.1.3
  smooth_star_rating: ^1.1.1
  http: ^0.12.1
  url_launcher: ^5.4.11
  flutter_svg: ^0.17.4
  firebase_auth: ^0.16.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.11
  fluttertoast: ^5.0.1
  intl: ^0.16.1
  flutter_full_pdf_viewer: ^1.0.6
  pdf: ^1.9.0
  flutter_barcode_scanner: ^1.0.1
  qr_flutter: ^3.2.0
  emoji_picker: ^0.1.0
  cached_network_image: ^2.2.0+1
  file_picker: 1.11.0
  permission_handler: 3.0.0
  focused_menu: ^1.0.1
  esys_flutter_share: ^1.0.2
  matrix_gesture_detector: ^0.1.0
  flutter_pdfview: ^1.0.3+1
  gradient_app_bar: ^0.1.3
  cloud_firestore: ^0.13.7
  overlay_support: ^1.0.5
  geolocator: ^5.3.2+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner:

dependency_overrides:
  dartx: ^0.3.0
  path: ^1.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avatar.png
    - assets/images/
    - assets/images/svg/
    - assets/images/svg/Saree.svg
    - assets/images/svg/kurti.svg
    - assets/images/svg/suit.svg
    - assets/images/svg/dress.svg
    - assets/images/svg/ethnic.svg
    - assets/images/svg/fabric.svg
    - assets/images/tax/
    - assets/images/Printed.jpg
    - assets/images/Saree.png
    - assets/images/business/
    - assets/images/assign.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Palatino Linotype
      fonts:
        - asset: assets/fonts/palatino-linotype.ttf
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/SEGOEUI.ttf
    - family: Segoe UI L
      fonts:
        - asset: assets/fonts/segoeuil.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
